### Obtener todos los roles
GET http://localhost:3000/api/roles

### Obtener un rol por ID
GET http://localhost:3000/api/roles/2

### Crear un nuevo rol
POST http://localhost:3000/api/roles
Content-Type: application/json

{
  "name": "Admin2",
  "enabled": true
}

### Actualizar un rol por ID
PUT http://localhost:3000/api/roles/1
Content-Type: application/json

{
  "name": "User"
}

### Soft Delete (marcar como deshabilitado)
DELETE http://localhost:3000/api/roles/1
